### ISSUE TITLE
allow users to sign-up the the mailing list via a Google form embedded in the footer

### ISSUE THREAD

**Issue by dannyhope** [dannyhope/uxbrighton#149]
- [x] make the doc
- [x] make the form
- [ ] embed it in the footer
- [ ] add JS to update the page with a thanks message

**Comment by dannyhope** [comment]
The form: http://jsbin.com/tirinehiko/1/edit

**Comment by jaygooby** [comment]
Here's the main bin: http://jsbin.com/vuciq/1/edit?html,js

It embeds this bin: http://jsbin.com/rijuda/1/edit?html - which is just the Google &lt;form&gt; html
But it doesn't submit it you run it in the editor: you need to test it by looking at the output URL: 

http://jsbin.com/vuciq/1

**Comment by jaygooby** [comment]
Implemented in 43d79013980af28e908a8ee7069da9677a4b49f6
