### ISSUE TITLE
tidy footer

### ISSUE THREAD

**Issue by dannyhope** [dannyhope/uxbrighton#173]
I thought that the footer could do with a little tweaking to make it less obtrucive (about 60% less, in fact), so I took the opportunity to tweak the design a little.

This shows the current implementation (top) and the tweaked design (bottom).

![image](https://cloud.githubusercontent.com/assets/22055/6233257/8e347354-b6c9-11e4-919a-239689f3be58.png)
- This design will compress down to 320 px wide
- None of the form elements or links should wrap
- There should be a min width of 320 px on the menu
- There should be a max width of 450 px on the menu

**Comment by dannyhope** [comment]
I know you’ll think me a pedant but…

- [ ] replace "you@yours.com" with "Email address"
- [ ] make title paler grey
- [ ] make title paler bold
- [ ] make the button less rounded
- [ ] make icons smaller
- [ ] make icons rgb(248, 201, 245)
- [ ] same size gutter around form as around links
- [ ] prevent form elements from wrapping
- [ ] apply min width of 320 px to the menu
- [ ] apply max width of 450 px to the menu

![screen shot 2015-02-26 at 16 48 40](https://cloud.githubusercontent.com/assets/22055/6396646/8f7d252a-bdd7-11e4-9614-fa391b4dec32.png)

**Comment by alexandtheweb** [comment]
@dannyhope I don't mind doing the spit and polish on this - feel free to reassign to me

**Comment by alexandtheweb** [comment]
@dannyhope Pushed most of these changes but still have a few questions: 
 
- make title paler grey - What color value?
- make title paler bold - Not sure what this means but changed weight from 500 to 300. 
- make the button less rounded - Previous border radius was 4px but dropped to 2px
- make icons smaller - How much smaller?
- make icons rgb(248, 201, 245) - This is a shade of magenta - guessing not what you meant? Also, what hover value?

**Comment by alexandtheweb** [comment]
@dannyhope Did you have a chance to look at comments above? Or can I close?

**Comment by dannyhope** [comment]
Can’t answer those questions right now but it’s done once it looks like this
![screen shot 2015-03-24 at 09 05 15](https://cloud.githubusercontent.com/assets/22055/6798433/eccb7948-d204-11e4-8e8e-92f924a68ab6.png)

**Comment by dannyhope** [comment]
defunct design, no longer with tweaking
