### ISSUE TITLE
Better event previews for Slack etc

### ISSUE THREAD

**Issue by jaygooby** [dannyhope/uxbrighton#194]
We're missing the headers that make decent [unfurling links](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.q62p2j885) for Facebook, Slack etc.

This preview should show event details, not the homepage blurb:

![screen shot 2016-04-26 at 20 00 22](https://cloud.githubusercontent.com/assets/64270/14830666/a974a4b0-0be9-11e6-866a-8c079ef9f1df.png)

**Comment by dannyhope** [comment]
Well spotted this is something we should definitely fix ASAP

On 26 April 2016 at 20:01, Jay Caines-Gooby <notifications@github.com>
wrote:

> We're missing the headers that make decent unfurling links
> <https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.q62p2j885>
> for Facebook, Slack etc.
>
> This preview should show event details, not the homepage blurb:
>
> [image: screen shot 2016-04-26 at 20 00 22]
> <https://cloud.githubusercontent.com/assets/64270/14830666/a974a4b0-0be9-11e6-866a-8c079ef9f1df.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dannyhope/uxbrighton/issues/194>
>



-- 
Danny Hope
http://dannyhope.co.uk
07595226792
